<?php
require_once __DIR__ . '/partials/auth_check.php';
require_once __DIR__ . '/../includes/db.php';

$admin_id = $_SESSION['admin_id'] ?? 0;

// Fetch settings
function get_set($key, $default, $uid) {
    global $conn;
    $stmt = $conn->prepare("SELECT setting_value FROM settings WHERE setting_key = ? AND user_id = ?");
    $stmt->bind_param("si", $key, $uid);
    $stmt->execute();
    $res = $stmt->get_result();
    $row = $res->fetch_assoc();
    return ($row && !empty($row['setting_value'])) ? $row['setting_value'] : $default;
}

$restaurant_name = get_set('restaurant_name', 'Our Menu', $admin_id);
$restaurant_sub  = get_set('restaurant_sub',  'Signature Selection', $admin_id);

// Fetch dishes grouped by category
$result = $conn->query(
    "SELECT d.name, d.price, d.image, c.name AS category
     FROM dishes d
     JOIN categories c ON c.id = d.category_id
     WHERE d.user_id = $admin_id AND d.is_deleted = 0
     ORDER BY c.name, d.name"
);
$dishes  = $result->fetch_all(MYSQLI_ASSOC);
$grouped = [];
foreach ($dishes as $d) { $grouped[$d['category']][] = $d; }
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Vingo Menu PDF Generation</title>
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;800&display=swap" rel="stylesheet">
<style>
  :root { 
    --primary: #111; 
    --accent: #6c63ff;
    --base-font-size: 16px;
    --name-size: 16px;
    --price-size: 16px;
    --cat-size: 20px;
    --title-size: 36px;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { 
    font-family: 'Outfit', sans-serif; 
    background: #fff; 
    padding: 40px; 
    color: #1a1a1a; 
    font-size: var(--base-font-size);
  }
  
  .header { text-align: center; margin-bottom: 40px; position: relative; }
  .header h1 { font-size: var(--title-size); font-weight: 800; letter-spacing: -1.5px; margin-bottom: 4px; color: var(--primary); }
  .header p { color: #888; font-size: 13px; text-transform: uppercase; letter-spacing: 3px; font-weight: 700; }
  .header::after { content: ''; display: block; width: 60px; height: 3px; background: var(--accent); margin: 16px auto 0; border-radius: 2px; }

  .category-section { margin-bottom: 40px; break-inside: avoid; }
  .category-title { 
    font-size: var(--cat-size); 
    font-weight: 800; 
    text-transform: uppercase; 
    letter-spacing: 1.5px; 
    color: var(--accent);
    margin-bottom: 20px;
    display: flex;
    align-items: center;
    gap: 12px;
  }
  .category-title::after { content: ''; flex: 1; height: 1px; background: #f0f0f0; }
  
  .dish-grid { 
    display: grid; 
    grid-template-columns: 1fr 1fr; 
    gap: 32px; 
    column-rule: 1px solid #f0f0f0;
  }
  
  .dish { 
    display: flex; 
    flex-direction: column; 
    gap: 4px;
    padding-bottom: 12px;
    border-bottom: 1px solid #fafafa;
    break-inside: avoid;
  }
  .dish-header { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; }
  .dish-name { font-size: var(--name-size); font-weight: 700; color: #111; }
  .dish-dots { flex: 1; border-bottom: 1px dotted #ccc; height: 3px; }
  .dish-price { font-weight: 800; color: var(--accent); font-size: var(--price-size); }

  .footer { 
    margin-top: 80px; 
    text-align: center; 
    font-size: 11px; 
    color: #bbb; 
    border-top: 1px solid #f0f0f0; 
    padding-top: 24px; 
    text-transform: uppercase;
    letter-spacing: 1px;
  }

  @media print {
    body { padding: 0; }
    .no-print { display: none; }
    @page { margin: 1.5cm; }
  }
</style>
</head>
<body>

<div class="header">
  <h1><?= htmlspecialchars($restaurant_name) ?></h1>
  <p><?= htmlspecialchars($restaurant_sub) ?></p>
</div>

<?php foreach ($grouped as $cat => $items): ?>
  <div class="category-section">
    <div class="category-title">
      <span><?= htmlspecialchars($cat) ?></span>
    </div>
    <div class="dish-grid">
      <?php foreach ($items as $d): ?>
        <div class="dish">
          <div class="dish-header">
            <div class="dish-name"><?= htmlspecialchars($d['name']) ?></div>
            <div class="dish-dots"></div>
            <div class="dish-price">₹<?= number_format($d['price'], 0) ?></div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
<?php endforeach; ?>

<div class="footer">
  Dynamically Generated by Vingo Menu Manager &copy; <?= date('Y') ?> • vingo-menu.com
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<script>
  window.onload = () => {
    // Apply saved font size from localStorage
    const savedSize = localStorage.getItem('menu_print_fontsize');
    if (savedSize) {
        const size = parseFloat(savedSize);
        const root = document.documentElement;
        root.style.setProperty('--base-font-size', size + 'px');
        root.style.setProperty('--name-size', size + 'px');
        root.style.setProperty('--price-size', size + 'px');
        root.style.setProperty('--cat-size', (size * 1.25) + 'px');
        root.style.setProperty('--title-size', (size * 2.25) + 'px');
        console.log(`[PDF] Applied saved font size: ${size}px`);
    }

    const element = document.body;
    const opt = {
      margin:       [10, 10, 10, 10],
      filename:     '<?= addslashes(str_replace(" ", "_", $restaurant_name)) ?>_Menu.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, letterRendering: true },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // Use a slight timeout to ensure styles and fonts are ready
    setTimeout(() => {
      html2pdf().set(opt).from(element).save().then(() => {
        // Optional: window.close(); 
      });
    }, 1000);
  };
</script>
</body>
</html>
